application: ruokakori
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: site/favicon.ico
  upload: site/favicon\.ico

- url: /stylesheets
  static_dir: site/stylesheets

- url: /js
  static_dir: site/js
  
- url: /pics
  static_dir: site/pics

- url: /robots\.txt
  static_files: static/robots.txt
  upload: static/robots\.txt

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: latest

- name: jinja2
  version: latest